# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-18 18:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('car_number', models.IntegerField()),
                ('response', models.CharField(max_length=500)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Cars')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('desc', models.CharField(max_length=500)),
                ('amount', models.IntegerField()),
                ('ticket_price', models.IntegerField()),
                ('points', models.IntegerField()),
                ('detention', models.IntegerField(choices=[(1, '1 year'), (2, '3 months'), (3, '6 months'), (4, '1 month'), (5, 'None')], default=5)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='violation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Violation'),
        ),
    ]
