# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-18 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='name',
        ),
        migrations.AddField(
            model_name='cars',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='violation',
            name='detention',
            field=models.IntegerField(choices=[(1, '1 year'), (2, '3 months'), (3, '6 months'), (4, '1 month'), (5, '15 days'), (6, 'None')], default=6),
        ),
    ]
