# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-18 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171118_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='violation_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Cars'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='violation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Violation'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
