# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-18 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20171118_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='violation_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
